#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Select an activity type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Activity_TypeCode
	{
		
		/// <summary>
		/// Appointment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Appointment", 1, null, "Appointment")]
		Appointment = 4201,
		
		/// <summary>
		/// Email
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 4, null, "Email")]
		Email = 4202,
		
		/// <summary>
		/// Fax
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fax", 3, null, "Fax")]
		Fax = 4204,
		
		/// <summary>
		/// Letter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Letter", 2, null, "Letter")]
		Letter = 4207,
		
		/// <summary>
		/// Phone Call
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Phone Call", 0, null, "Phone Call")]
		PhoneCall = 4210,
	}
}
#pragma warning restore CS1591
