#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Type of entity with which the activity attachment is associated.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ActivityFileAttachment_ObjectCode
	{
		
		/// <summary>
		/// Post
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Post", 0, null, "Post")]
		Post = 8000,
		
		/// <summary>
		/// Post Comment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Post Comment", 1, null, "Post Comment")]
		PostComment = 8005,
	}
}
#pragma warning restore CS1591
