#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Select where to add the marketing list
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AddListCampaign
	{
		
		/// <summary>
		/// To the campaign and all undistributed campaign activities.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("To the campaign and all undistributed campaign activities.", 0, null, "To the campaign and all undistributed campaign activities.")]
		Tothecampaignandallundistributedcampaignactivities = 1,
		
		/// <summary>
		/// To the campaign only.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("To the campaign only.", 1, null, "To the campaign only.")]
		Tothecampaignonly = 0,
	}
}
#pragma warning restore CS1591
