#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BotComponentCollectionSharingRoleType
	{
		
		/// <summary>
		/// Can author the component collection
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Component collection author", 2, "#0000ff", "Can author the component collection")]
		Componentcollectionauthor = 3,
		
		/// <summary>
		/// Has access to the content of the component collection and can add component collection to the copilot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Component collection user", 1, "#0000ff", "Has access to the content of the component collection and can add component colle" +
			"ction to the copilot")]
		Componentcollectionuser = 2,
		
		/// <summary>
		/// Copilot user has access to the content of the component collection
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Copilot user", 0, "#0000ff", "Copilot user has access to the content of the component collection")]
		Copilotuser = 1,
	}
}
#pragma warning restore CS1591
