#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Options to cascade closing cases
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CascadeCaseClosurePreference
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Close all child cases when parent case is closed", 0)]
		Closeallchildcaseswhenparentcaseisclosed = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Don\'t allow parent case closure until all child cases are closed", 1)]
		Dontallowparentcaseclosureuntilallchildcasesareclosed = 1,
	}
}
#pragma warning restore CS1591
