#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Select the type of sales entity which the campaign response should be converted to
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Convert_Campaign_Response_Sales_Entity_Type
	{
		
		/// <summary>
		/// Opportunity Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Opportunity", 0, null, "Opportunity Label")]
		Opportunity = 1,
		
		/// <summary>
		/// Order Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Order", 1, null, "Order Label")]
		Order = 2,
		
		/// <summary>
		/// Quote Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quote", 2, null, "Quote Label")]
		Quote = 3,
	}
}
#pragma warning restore CS1591
