#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Select the option for converting the campaign response
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Convert_Campaign_Response_Option
	{
		
		/// <summary>
		/// Close response label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Close response", 3, null, "Close response label")]
		Closeresponse = 4,
		
		/// <summary>
		/// Convert to existing lead label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Convert to an existing lead", 1, null, "Convert to existing lead label")]
		Converttoanexistinglead = 2,
		
		/// <summary>
		/// Create lead label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Create a lead", 0, null, "Create lead label")]
		Createalead = 1,
		
		/// <summary>
		/// Create sales entity label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Create a quote, order, or opportunity for an account or contact", 2, null, "Create sales entity label")]
		Createaquoteorderoropportunityforanaccountorcontact = 3,
	}
}
#pragma warning restore CS1591
