#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Select the status for the deactivated campaign response
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Convert_Campaign_Response_Deactivate_Status
	{
		
		/// <summary>
		/// Cancelled Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cancelled", 1, null, "Cancelled Label")]
		Cancelled = 2,
		
		/// <summary>
		/// Closed Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Closed", 0, null, "Closed Label")]
		Closed = 1,
	}
}
#pragma warning restore CS1591
