#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Select the option for converting the campaign response to a lead
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Convert_Campaign_Response_To_Lead_Option
	{
		
		/// <summary>
		/// Disqualify Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Disqualify", 1, null, "Disqualify Label")]
		Disqualify = 2,
		
		/// <summary>
		/// Qualify Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Qualify and convert into the following records", 0, null, "Qualify Label")]
		Qualifyandconvertintothefollowingrecords = 1,
	}
}
#pragma warning restore CS1591
