#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// How would you like to delete this series?
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Delete_RecurringAppointmentMaster
	{
		
		/// <summary>
		/// Delete all instances
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("All instances", 0, null, "Delete all instances")]
		Allinstances = 1,
		
		/// <summary>
		/// Delete all series except the past appointments
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("The series, leave past appointments", 1, null, "Delete all series except the past appointments")]
		Theseriesleavepastappointments = 2,
	}
}
#pragma warning restore CS1591
