#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Option set for the different possible forms to use for incident/case resolution
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum IncidentResolutionFormType
	{
		
		/// <summary>
		/// MFD
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customizable dialog", 1, "#0000ff", "MFD")]
		Customizabledialog = 2,
		
		/// <summary>
		/// Quick create form
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quick create dialog", 2, "#0000ff", "Quick create form")]
		Quickcreatedialog = 3,
		
		/// <summary>
		/// MDD
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Standard dialog", 0, "#0000ff", "MDD")]
		Standarddialog = 1,
	}
}
#pragma warning restore CS1591
