#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// The role is inherited
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum IsInherited
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Direct User (Basic) access level and Team privileges", 1)]
		DirectUserBasicaccesslevelandTeamprivileges = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Team privileges only", 0)]
		Teamprivilegesonly = 0,
	}
}
#pragma warning restore CS1591
