#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// List of Mobile Offline Enabled Entities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MobileOfflineEnabledEntities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Account", 0)]
		Account = 1,
		
		/// <summary>
		/// Beschreibung.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AccountLeads", 18, null, "Beschreibung.")]
		AccountLeads = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Activity File Attachment", 12)]
		ActivityFileAttachment = 10184,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agreement Business Process", 75)]
		AgreementBusinessProcess = 11026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Appointment", 8)]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Asset Category Template Association", 86)]
		AssetCategoryTemplateAssociation = 10380,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Asset Template Association", 87)]
		AssetTemplateAssociation = 10381,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Attachment", 5)]
		Attachment = 1001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bookable Resource", 81)]
		BookableResource = 1150,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bookable Resource Booking", 82)]
		BookableResourceBooking = 1145,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bookable Resource Booking Quick Note", 88)]
		BookableResourceBookingQuickNote = 11085,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Booking Status", 83)]
		BookingStatus = 1152,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Booking Timestamp", 89)]
		BookingTimestamp = 11023,
		
		/// <summary>
		/// Anfrage für Serviceanforderung, die einem Vertrag zugeordnet ist.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Case", 34, null, "Anfrage für Serviceanforderung, die einem Vertrag zugeordnet ist.")]
		Case = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Case to Work Order Business Process", 74)]
		CasetoWorkOrderBusinessProcess = 11025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CFS - IoT Alert Process Flow", 131)]
		CFSIoTAlertProcessFlow = 11103,
		
		/// <summary>
		/// Unternehmen, das bei dem durch einen Lead oder eine Verkaufschance dargestellten Verkauf als Mitbewerber auftritt.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Competitor", 60, null, "Unternehmen, das bei dem durch einen Lead oder eine Verkaufschance dargestellten " +
			"Verkauf als Mitbewerber auftritt.")]
		Competitor = 123,
		
		/// <summary>
		/// Zusätzliche Adressen eines Mitbewerbers. Die ersten beiden Adressen werden im Mitbewerberobjekt gespeichert.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Competitor Address", 52, null, "Zusätzliche Adressen eines Mitbewerbers. Die ersten beiden Adressen werden im Mit" +
			"bewerberobjekt gespeichert.")]
		CompetitorAddress = 1004,
		
		/// <summary>
		/// Zuordnung zwischen einem Mitbewerber und einem Produkt, das von einem Mitbewerber angeboten wird.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Competitor Product", 53, null, "Zuordnung zwischen einem Mitbewerber und einem Produkt, das von einem Mitbewerber" +
			" angeboten wird.")]
		CompetitorProduct = 1006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Connection", 37)]
		Connection = 3234,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Connection Role", 38)]
		ConnectionRole = 3231,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Contact", 1)]
		Contact = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ContactLeads", 19)]
		ContactLeads = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Currency", 66)]
		Currency = 9105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer Asset", 90)]
		CustomerAsset = 10382,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer Asset Category", 91)]
		CustomerAssetCategory = 10386,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 9)]
		Email = 4202,
		
		/// <summary>
		/// Definiert Umfang und Typ des Supports für einen Kunden.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entitlement", 30, null, "Definiert Umfang und Typ des Supports für einen Kunden.")]
		Entitlement = 9700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entitlement Contact", 31)]
		EntitlementContact = 7272,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entitlement Product", 32)]
		EntitlementProduct = 6363,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entitlement Template Product", 33)]
		EntitlementTemplateProduct = 4545,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entity Attachment", 67)]
		EntityAttachment = 10649,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Field Service Price List Item", 92)]
		FieldServicePriceListItem = 11029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Field Service Setting", 93)]
		FieldServiceSetting = 11030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Functional Location", 94)]
		FunctionalLocation = 10387,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Functional Location Type", 95)]
		FunctionalLocationType = 10388,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Functional Location Type Template Association", 102)]
		FunctionalLocationTypeTemplateAssociation = 10390,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Geolocation Settings", 132)]
		GeolocationSettings = 11104,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Image Descriptor", 17)]
		ImageDescriptor = 1007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Incident KnowledgeBaseRecord", 35)]
		IncidentKnowledgeBaseRecord = 9931,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Incident Type", 96)]
		IncidentType = 11033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Incident Type Product", 97)]
		IncidentTypeProduct = 11035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Incident Type Resolution", 98)]
		IncidentTypeResolution = 11091,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Incident Type Service", 99)]
		IncidentTypeService = 11036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Incident Type Service Task", 100)]
		IncidentTypeServiceTask = 11037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Incident Types Setup", 79)]
		IncidentTypesSetup = 11038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inspection Attachment", 70)]
		InspectionAttachment = 10996,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inspection Response", 72)]
		InspectionResponse = 10999,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inspection Template", 69)]
		InspectionTemplate = 10995,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inspection Template Version", 71)]
		InspectionTemplateVersion = 10997,
		
		/// <summary>
		/// Auftrag, der in Rechnung gestellt wurde.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Invoice", 62, null, "Auftrag, der in Rechnung gestellt wurde.")]
		Invoice = 1090,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Invoice Product", 63)]
		InvoiceProduct = 1091,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Alert", 39)]
		IoTAlert = 10404,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Alert to Case Process", 51)]
		IoTAlerttoCaseProcess = 10420,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Device", 40)]
		IoTDevice = 10405,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Device Category", 41)]
		IoTDeviceCategory = 10406,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Device Command", 42)]
		IoTDeviceCommand = 10407,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Device Command Definition", 43)]
		IoTDeviceCommandDefinition = 10408,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Device Data History", 44)]
		IoTDeviceDataHistory = 10409,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Device Property", 45)]
		IoTDeviceProperty = 10410,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Device Registration History", 46)]
		IoTDeviceRegistrationHistory = 10411,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Property Definition", 47)]
		IoTPropertyDefinition = 10414,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Provider", 48)]
		IoTProvider = 10415,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Provider Instance", 49)]
		IoTProviderInstance = 10416,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Settings", 50)]
		IoTSettings = 10417,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Knowledge Article", 84)]
		KnowledgeArticle = 9953,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Knowledge Article Attachment", 14)]
		KnowledgeArticleAttachment = 10199,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Knowledge Article Image", 13)]
		KnowledgeArticleImage = 10193,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Knowledge Article Views", 85)]
		KnowledgeArticleViews = 9955,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lead", 20)]
		Lead = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("LeadCompetitors", 54)]
		LeadCompetitors = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("LeadProduct", 55)]
		LeadProduct = 27,
		
		/// <summary>
		/// Lead für Verkaufschance Vertriebsprozess Geschäftsprozessfluss
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lead To Opportunity Sales Process", 56, null, "Lead für Verkaufschance Vertriebsprozess Geschäftsprozessfluss")]
		LeadToOpportunitySalesProcess = 954,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Location Template Association", 101)]
		LocationTemplateAssociation = 10389,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("MobileSource", 133)]
		MobileSource = 11115,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Note", 2)]
		Note = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not-to-exceed", 103)]
		Nottoexceed = 11093,
		
		/// <summary>
		/// Potenzielles Umsatz generierendes Ereignis oder ein Verkauf an ein Konto, das bzw. der durch einen Vertriebsprozess bis zum Abschluss nachverfolgt werden muss.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Opportunity", 57, null, "Potenzielles Umsatz generierendes Ereignis oder ein Verkauf an ein Konto, das bzw" +
			". der durch einen Vertriebsprozess bis zum Abschluss nachverfolgt werden muss.")]
		Opportunity = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OpportunityCompetitors", 58)]
		OpportunityCompetitors = 25,
		
		/// <summary>
		/// Zuordnung zwischen einer Verkaufschance und einem Produkt.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Opportunity Line", 80, null, "Zuordnung zwischen einer Verkaufschance und einem Produkt.")]
		OpportunityLine = 1083,
		
		/// <summary>
		/// Verkaufschance Vertriebsprozess Geschäftsprozessfluss
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Opportunity Sales Process", 59, null, "Verkaufschance Vertriebsprozess Geschäftsprozessfluss")]
		OpportunitySalesProcess = 953,
		
		/// <summary>
		/// Angebot, das angenommen wurde.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Order", 65, null, "Angebot, das angenommen wurde.")]
		Order = 1088,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Order Line", 78)]
		OrderLine = 1089,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OrganizationDataSyncFnoState", 15)]
		OrganizationDataSyncFnoState = 10221,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OrganizationDataSyncState", 16)]
		OrganizationDataSyncState = 10222,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Phone Call", 129)]
		PhoneCall = 4210,
		
		/// <summary>
		/// Telefon-zu-Anfrage-Prozess Geschäftsprozessfluss
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Phone To Case Process", 36, null, "Telefon-zu-Anfrage-Prozess Geschäftsprozessfluss")]
		PhoneToCaseProcess = 952,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Price List", 25)]
		PriceList = 1022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Price List Item", 26)]
		PriceListItem = 1026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Priority", 104)]
		Priority = 10973,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Product", 21)]
		Product = 1024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Product Inventory", 105)]
		ProductInventory = 11052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Product Relationship", 27)]
		ProductRelationship = 1028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Property", 22)]
		Property = 1048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Property Asset Association", 107)]
		PropertyAssetAssociation = 10392,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Property Association", 23)]
		PropertyAssociation = 1235,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Property Definition", 106)]
		PropertyDefinition = 10391,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Property Instance", 61)]
		PropertyInstance = 1333,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Property Location Association", 108)]
		PropertyLocationAssociation = 10393,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Property Log", 109)]
		PropertyLog = 10394,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Property Option Set Item", 24)]
		PropertyOptionSetItem = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Property Template Association", 110)]
		PropertyTemplateAssociation = 10395,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Purchase Order Business Process", 73)]
		PurchaseOrderBusinessProcess = 11024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue", 6)]
		Queue = 2020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue Item", 7)]
		QueueItem = 2029,
		
		/// <summary>
		/// Formelles Angebot für Produkte und/oder Services zu bestimmten Preisen und entsprechenden Zahlungsbedingungen, das an einen potenziellen Kunden gesendet wird.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quote", 64, null, "Formelles Angebot für Produkte und/oder Services zu bestimmten Preisen und entspr" +
			"echenden Zahlungsbedingungen, das an einen potenziellen Kunden gesendet wird.")]
		Quote = 1084,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quote Line", 77)]
		QuoteLine = 1085,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Resolution", 111)]
		Resolution = 11096,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Scheduling Parameter", 68)]
		SchedulingParameter = 10984,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Service Task Type", 112)]
		ServiceTaskType = 11071,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SLA KPI Instance", 11)]
		SLAKPIInstance = 9752,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Task", 10)]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tax Code", 113)]
		TaxCode = 11008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Team", 4)]
		Team = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Template For Properties", 114)]
		TemplateForProperties = 10396,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Territory", 130)]
		Territory = 2013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Time Entry", 115)]
		TimeEntry = 11000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Time Off Request", 117)]
		TimeOffRequest = 11072,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Time Source", 116)]
		TimeSource = 11001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Trade", 118)]
		Trade = 11097,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Unit", 28)]
		Unit = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Unit Group", 29)]
		UnitGroup = 1056,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("User", 3)]
		User = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Warehouse", 119)]
		Warehouse = 11010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order", 120)]
		WorkOrder = 11074,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order Business Process", 76)]
		WorkOrderBusinessProcess = 11027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order Incident", 121)]
		WorkOrderIncident = 11077,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work order not-to-exceed", 122)]
		Workordernottoexceed = 11101,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order Product", 123)]
		WorkOrderProduct = 11078,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order Resolution", 124)]
		WorkOrderResolution = 11102,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order Service", 125)]
		WorkOrderService = 11080,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order Service Task", 126)]
		WorkOrderServiceTask = 11081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order Substatus", 127)]
		WorkOrderSubstatus = 11082,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order Type", 128)]
		WorkOrderType = 11083,
	}
}
#pragma warning restore CS1591
