#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Booking Status Optimization Methods
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_BookingStatusOptimizationMethod
	{
		
		/// <summary>
		/// Bookings in this status will not be moved by the optimization engine
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Do Not Move", 1, "#0000ff", "Bookings in this status will not be moved by the optimization engine")]
		DoNotMove = 192350001,
		
		/// <summary>
		/// Bookings in this status will be completely ignored by the optimization engine
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ignore", 2, "#0000ff", "Bookings in this status will be completely ignored by the optimization engine")]
		Ignore = 192350002,
		
		/// <summary>
		/// Bookings in this status can be optimized by the optimization engine
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Optimize", 0, "#0000ff", "Bookings in this status can be optimized by the optimization engine")]
		Optimize = 192350000,
	}
}
#pragma warning restore CS1591
