#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// This option set is used to list different Mapping Types.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_IotMappingType
	{
		
		/// <summary>
		/// Map the device identifier.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Device identifier", 0, "#0000ff", "Map the device identifier.")]
		Deviceidentifier = 192350000,
		
		/// <summary>
		/// Map a device property.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Device property", 2, "#0000ff", "Map a device property.")]
		Deviceproperty = 192350002,
		
		/// <summary>
		/// Map the rule identifier.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Rule identifier", 1, "#0000ff", "Map the rule identifier.")]
		Ruleidentifier = 192350001,
	}
}
#pragma warning restore CS1591
