#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_FieldServiceAutoNumberingEntities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agreement", 1, "#0000ff", "", "msdyn_agreement")]
		Agreement = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inventory Adjustment", 2, "#0000ff", "", "msdyn_inventoryadjustment")]
		InventoryAdjustment = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inventory Transfer", 3, "#0000ff", "", "msdyn_inventorytransfer")]
		InventoryTransfer = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Purchase Order", 4, "#0000ff", "", "msdyn_purchaseorder")]
		PurchaseOrder = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RMA", 5, "#0000ff", "", "msdyn_rma")]
		RMA = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RTV", 6, "#0000ff", "", "msdyn_rtv")]
		RTV = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order", 0, "#0000ff", "", "msdyn_workorder")]
		WorkOrder = 0,
	}
}
#pragma warning restore CS1591
