#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Defines type of the rule
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_UnifiedRoutingDiagnostic_Msdyn_RuleType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Assignment", 5, "#0000ff")]
		Assignment = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Assignment Selection Criteria", 6, "#0000ff")]
		AssignmentSelectionCriteria = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Custom API Classification", 8, "#0000ff")]
		CustomAPIClassification = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Custom API Route to Queue", 9, "#0000ff")]
		CustomAPIRoutetoQueue = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Demand Classification", 0, "#0000ff")]
		DemandClassification = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ICD Route To Queue", 10, "#0000ff")]
		ICDRouteToQueue = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Intake", 7, "#0000ff")]
		Intake = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ML", 3, "#0000ff")]
		ML = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Prioritization", 4, "#0000ff")]
		Prioritization = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Route To Queue", 1, "#0000ff")]
		RouteToQueue = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Skill Identification", 2, "#0000ff")]
		SkillIdentification = 3,
	}
}
#pragma warning restore CS1591
