#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// This option set is used to list different Field Data Formats.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_IotFieldDataFormat
	{
		
		/// <summary>
		/// The field directly contains the value.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Direct", 0, "#0000ff", "The field directly contains the value.")]
		Direct = 192350000,
		
		/// <summary>
		/// The field contains a JSON containing the value desired.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("JSON", 1, "#0000ff", "The field contains a JSON containing the value desired.")]
		JSON = 192350001,
	}
}
#pragma warning restore CS1591
