#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Used to identify the type of dependency that the requirements need to satisfy
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_RequirementDependencyType
	{
		
		/// <summary>
		/// Used when the dependent requirement needs to start after the end of the other requirement.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Start After End", 0, "#0000ff", "Used when the dependent requirement needs to start after the end of the other req" +
			"uirement.")]
		StartAfterEnd = 192350000,
	}
}
#pragma warning restore CS1591
