#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_CI_Locale
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-ae", 13, "#0000ff")]
		arae = 140,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-bh", 14, "#0000ff")]
		arbh = 150,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-eg", 15, "#0000ff")]
		areg = 160,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-iq", 16, "#0000ff")]
		ariq = 170,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-jo", 17, "#0000ff")]
		arjo = 180,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-kw", 18, "#0000ff")]
		arkw = 190,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-lb", 19, "#0000ff")]
		arlb = 200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-om", 20, "#0000ff")]
		arom = 210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-qa", 21, "#0000ff")]
		arqa = 220,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-sa", 22, "#0000ff")]
		arsa = 230,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-sy", 23, "#0000ff")]
		arsy = 240,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("da-dk", 25, "#0000ff")]
		dadk = 260,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("de-de", 2, "#0000ff")]
		dede = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("en-gb", 1, "#0000ff")]
		engb = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("en-us", 0, "#0000ff")]
		enus = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("es-es", 5, "#0000ff")]
		eses = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("es-mx", 6, "#0000ff")]
		esmx = 60,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("fi-fi", 27, "#0000ff")]
		fifi = 280,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("fr-ca", 11, "#0000ff")]
		frca = 120,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("fr-fr", 3, "#0000ff")]
		frfr = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("he-il", 24, "#0000ff")]
		heil = 250,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("it-it", 4, "#0000ff")]
		itit = 40,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ja-jp", 7, "#0000ff")]
		jajp = 70,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("nb-no", 28, "#0000ff")]
		nbno = 290,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("nl-nl", 10, "#0000ff")]
		nlnl = 110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("pt-br", 8, "#0000ff")]
		ptbr = 80,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("pt-pt", 12, "#0000ff")]
		ptpt = 130,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sv-se", 26, "#0000ff")]
		svse = 270,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("zh-cn", 9, "#0000ff")]
		zhcn = 90,
	}
}
#pragma warning restore CS1591
