#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_StreamSource
	{
		
		/// <summary>
		/// Connect with customers via Apple Messages for Business channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Apple Messages for Business", 13, "#0000ff", "Connect with customers via Apple Messages for Business channel option")]
		AppleMessagesforBusiness = 192450000,
		
		/// <summary>
		/// Connect with customers via Co-browse channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Co-browse", 3, "#0000ff", "Connect with customers via Co-browse channel option")]
		Cobrowse = 192390000,
		
		/// <summary>
		/// Connect with customers via Custom channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Custom", 12, "#0000ff", "Connect with customers via Custom channel option")]
		Custom = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entity Records", 5, "#0000ff")]
		EntityRecords = 192350000,
		
		/// <summary>
		/// Connect with customers via Facebook channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Facebook", 7, "#0000ff", "Connect with customers via Facebook channel option")]
		Facebook = 192330000,
		
		/// <summary>
		/// Connect with customers via Google's Business Messages channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Google\'s Business Messages", 14, "#0000ff", "Connect with customers via Google\'s Business Messages channel option")]
		GooglesBusinessMessages = 192450001,
		
		/// <summary>
		/// Connect with customers via LINE channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("LINE", 8, "#0000ff", "Connect with customers via LINE channel option")]
		LINE = 192310000,
		
		/// <summary>
		/// Connect with customers via Live chat channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Live chat", 0, "#0000ff", "Connect with customers via Live chat channel option")]
		Livechat = 192360000,
		
		/// <summary>
		/// Connect with customers via Teams channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Microsoft Teams", 15, "#0000ff", "Connect with customers via Teams channel option")]
		MicrosoftTeams = 19241000,
		
		/// <summary>
		/// Connect with customers via Screen sharing channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Screen sharing", 4, "#0000ff", "Connect with customers via Screen sharing channel option")]
		Screensharing = 192400000,
		
		/// <summary>
		/// Connect with customers via SMS channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SMS", 6, "#0000ff", "Connect with customers via SMS channel option")]
		SMS = 192340000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Twitter", 11, "#0000ff")]
		Twitter = 192350001,
		
		/// <summary>
		/// Connect with customers via Video channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Video", 2, "#0000ff", "Connect with customers via Video channel option")]
		Video = 192380000,
		
		/// <summary>
		/// Connect with customers via Voice channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Voice", 1, "#0000ff", "Connect with customers via Voice channel option")]
		Voice = 192370000,
		
		/// <summary>
		/// Connect with customers via WeChat channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WeChat", 10, "#0000ff", "Connect with customers via WeChat channel option")]
		WeChat = 192320000,
		
		/// <summary>
		/// Connect with customers via WhatsApp channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WhatsApp", 9, "#0000ff", "Connect with customers via WhatsApp channel option")]
		WhatsApp = 192300000,
	}
}
#pragma warning restore CS1591
