#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Denotes the mode of consultation a participant has in a conversation
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_ConsultModeType
	{
		
		/// <summary>
		/// Chat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Chat", 0, null, "Chat")]
		Chat = 0,
		
		/// <summary>
		/// Chat And Voice
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Chat And Voice", 1, null, "Chat And Voice")]
		ChatAndVoice = 1,
		
		/// <summary>
		/// Voice
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Voice", 2, null, "Voice")]
		Voice = 2,
	}
}
#pragma warning restore CS1591
