#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Locale for personal message
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_PersonalMessage_LocaleField
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-SA", 12, "#0000ff")]
		arSA = 1025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("bg-BG", 26, "#0000ff")]
		bgBG = 1026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ca-ES", 27, "#0000ff")]
		caES = 1027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("cs-CZ", 22, "#0000ff")]
		csCZ = 1029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("da-DK", 0, "#0000ff")]
		daDK = 1030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("de-DE", 1, "#0000ff")]
		deDE = 1031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("el-GR", 28, "#0000ff")]
		elGR = 1032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("en-US", 3, "#0000ff")]
		enUS = 1033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("es-ES", 2, "#0000ff")]
		esES = 3082,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("et-EE", 29, "#0000ff")]
		etEE = 1061,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("eu-ES", 30, "#0000ff")]
		euES = 1069,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("fi-FI", 20, "#0000ff")]
		fiFI = 1035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("fr-FR", 4, "#0000ff")]
		frFR = 1036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("gl-ES", 31, "#0000ff")]
		glES = 1110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("he-IL", 23, "#0000ff")]
		heIL = 1037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("hi-IN", 32, "#0000ff")]
		hiIN = 1081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("hr-HR", 33, "#0000ff")]
		hrHR = 1050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("hu-HU", 34, "#0000ff")]
		huHU = 1038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("id-ID", 14, "#0000ff")]
		idID = 1057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("it-IT", 5, "#0000ff")]
		itIT = 1040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ja-JP", 7, "#0000ff")]
		jaJP = 1041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("kk-KZ", 35, "#0000ff")]
		kkKZ = 1087,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ko-KR", 21, "#0000ff")]
		koKR = 1042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("lt-LT", 36, "#0000ff")]
		ltLT = 1063,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("lv-LV", 37, "#0000ff")]
		lvLV = 1062,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("nb-NO", 8, "#0000ff")]
		nbNO = 1044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("nl-NL", 6, "#0000ff")]
		nlNL = 1043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("pl-PL", 15, "#0000ff")]
		plPL = 1045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("pt-BR", 9, "#0000ff")]
		ptBR = 1046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("pt-PT", 10, "#0000ff")]
		ptPT = 2070,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ro-RO", 16, "#0000ff")]
		roRO = 1048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ru-RU", 17, "#0000ff")]
		ruRU = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sk-SK", 38, "#0000ff")]
		skSK = 1051,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sr-Latn-CS", 39, "#0000ff")]
		srLatnCS = 2074,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sv-SE", 11, "#0000ff")]
		svSE = 1053,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("th-TH", 18, "#0000ff")]
		thTH = 1054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("tr-TR", 19, "#0000ff")]
		trTR = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("zh-CN", 13, "#0000ff")]
		zhCN = 2052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("zh-HK", 25, "#0000ff")]
		zhHK = 3076,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("zh-TW", 24, "#0000ff")]
		zhTW = 1028,
	}
}
#pragma warning restore CS1591
