#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Indicates the origin of the not-to-exceed amount.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_NTeSource
	{
		
		/// <summary>
		/// Indicates not-to-exceed amount was based on an approved quotation.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Approved quote", 2, "#FFFF00", "Indicates not-to-exceed amount was based on an approved quotation.")]
		Approvedquote = 192350300,
		
		/// <summary>
		/// Indicates not-to-exceed amount was based on a pre-negotiated not-to-exceed threshold.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not-to-exceed", 0, "#004DE6", "Indicates not-to-exceed amount was based on a pre-negotiated not-to-exceed thresh" +
			"old.")]
		Nottoexceed = 192350100,
		
		/// <summary>
		/// Indicates not-to-exceed amount was based on custom amount specified by the user.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("User-specified", 1, "#4CE600", "Indicates not-to-exceed amount was based on custom amount specified by the user.")]
		Userspecified = 192350200,
	}
}
#pragma warning restore CS1591
