#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Dynamics 365 Languages
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_LanguageCodes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("English(en-US)", 0, "#0000ff", "", "en-us")]
		EnglishenUS = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("French(fr-FR)", 1, "#0000ff", "", "fr-FR")]
		FrenchfrFR = 100000002,
	}
}
#pragma warning restore CS1591
