#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Crew Strategy used in crew management
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_CrewStrategy
	{
		
		/// <summary>
		/// Cascade and Accept Cascade Completely (Not Recommended)
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cascade and Accept Cascade Completely (Not Recommended)", 2, "#0000ff", "Cascade and Accept Cascade Completely (Not Recommended)")]
		CascadeandAcceptCascadeCompletelyNotRecommended = 192350000,
		
		/// <summary>
		/// Crew Leader Management
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Crew Leader Management", 0, "#0000ff", "Crew Leader Management")]
		CrewLeaderManagement = 192350001,
		
		/// <summary>
		/// Crew Member Self-Management
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Crew Member Self-Management", 1, "#0000ff", "Crew Member Self-Management")]
		CrewMemberSelfManagement = 192350002,
	}
}
#pragma warning restore CS1591
