#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Message Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_MessageType
	{
		
		/// <summary>
		/// Conversation will be created when sending this message.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Create conversation on send", 1, "#0000ff", "Conversation will be created when sending this message.")]
		Createconversationonsend = 100000001,
		
		/// <summary>
		/// Conversation will be only created when customer responds to this message.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Create conversation when customer responds ", 0, "#0000ff", "Conversation will be only created when customer responds to this message.")]
		Createconversationwhencustomerresponds = 100000000,
	}
}
#pragma warning restore CS1591
