#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Time
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_PlaybookActivity_Time
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("01:00 AM", 0, "#0000ff")]
		_0100AM = 100,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("01:00 PM", 12, "#0000ff")]
		_0100PM = 1300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("02:00 AM", 1, "#0000ff")]
		_0200AM = 200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("02:00 PM", 13, "#0000ff")]
		_0200PM = 1400,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("03:00 AM", 2, "#0000ff")]
		_0300AM = 300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("03:00 PM", 14, "#0000ff")]
		_0300PM = 1500,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("04:00 AM", 3, "#0000ff")]
		_0400AM = 400,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("04:00 PM", 15, "#0000ff")]
		_0400PM = 1600,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("05:00 AM", 4, "#0000ff")]
		_0500AM = 500,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("05:00 PM", 16, "#0000ff")]
		_0500PM = 1700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("06:00 AM", 5, "#0000ff")]
		_0600AM = 600,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("06:00 PM", 17, "#0000ff")]
		_0600PM = 1800,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("07:00 AM", 6, "#0000ff")]
		_0700AM = 700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("07:00 PM", 18, "#0000ff")]
		_0700PM = 1900,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("08:00 AM", 7, "#0000ff")]
		_0800AM = 800,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("08:00 PM", 19, "#0000ff")]
		_0800PM = 2000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("09:00 AM", 8, "#0000ff")]
		_0900AM = 900,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("09:00 PM", 20, "#0000ff")]
		_0900PM = 2100,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("10:00 AM", 9, "#0000ff")]
		_1000AM = 1000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("10:00 PM", 21, "#0000ff")]
		_1000PM = 2200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("11:00 AM", 10, "#0000ff")]
		_1100AM = 1100,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("11:00 PM", 22, "#0000ff")]
		_1100PM = 2300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("12:00 AM", 23, "#0000ff")]
		_1200AM = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("12:00 PM", 11, "#0000ff")]
		_1200PM = 1200,
	}
}
#pragma warning restore CS1591
