#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Defines the step type for routing configuration
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_RoutingConfigurationStepType
	{
		
		/// <summary>
		/// Identifies the agent group for the work-item
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent Group identification", 3, "#0000ff", "Identifies the agent group for the work-item")]
		AgentGroupidentification = 192350003,
		
		/// <summary>
		/// Enriches the work-item
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Enrichment", 0, "#0000ff", "Enriches the work-item")]
		Enrichment = 192350000,
		
		/// <summary>
		/// Identifies the queue for the work-item
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue identification", 2, "#0000ff", "Identifies the queue for the work-item")]
		Queueidentification = 192350002,
		
		/// <summary>
		/// Identifies the skills for the work-item
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Skill identification", 1, "#0000ff", "Identifies the skills for the work-item")]
		Skillidentification = 192350001,
	}
}
#pragma warning restore CS1591
