#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Communication Provider
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_OCCommunicationProvider
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Azure Communication Services", 0, "#0000ff")]
		AzureCommunicationServices = 192350000,
		
		/// <summary>
		/// TeleSign SMS provider
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("TeleSign", 2, "#0000ff", "TeleSign SMS provider")]
		TeleSign = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Twilio", 1, "#0000ff")]
		Twilio = 192350001,
	}
}
#pragma warning restore CS1591
