#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Define the authoring mode for the rule set
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_RuleSetAuthoringMode
	{
		
		/// <summary>
		/// Configure rule set with decision list control
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Decision list", 0, "#0000ff", "Configure rule set with decision list control")]
		Decisionlist = 192350000,
	}
}
#pragma warning restore CS1591
