#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_WidgetThemeColor
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Black", 4, "#000000", "", "#000000")]
		Black = 19236004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Blue", 2, "#315FA2", "", "#315FA2")]
		Blue = 19236002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Brown", 9, "#927200", "", "#927200")]
		Brown = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Clay", 10, "#A42B1A", "", "#A42B1A")]
		Clay = 192350006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Green", 3, "#358717", "", "#358717")]
		Green = 19236003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Grey", 7, "#767676", "", "#767676")]
		Grey = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Orange", 5, "#D24204", "", "#D24204")]
		Orange = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pink", 6, "#AD5889", "", "#AD5889")]
		Pink = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Purple", 11, "#691B88", "", "#691B88")]
		Purple = 192350007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Red", 0, "#BF0900", "", "#BF0900")]
		Red = 19236001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Teal", 1, "#00818A", "", "#00818A")]
		Teal = 192360017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Violet", 8, "#6A1E7A", "", "#6A1E7A")]
		Violet = 192350004,
	}
}
#pragma warning restore CS1591
