#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Bot Session Outcome option
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_SessionOutcome
	{
		
		/// <summary>
		/// Bot Session is abandoned
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("abandoned", 3, null, "Bot Session is abandoned")]
		abandoned = 419550003,
		
		/// <summary>
		/// Bot Session is escalated
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("escalated", 2, null, "Bot Session is escalated")]
		escalated = 419550002,
		
		/// <summary>
		/// None
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("none", 0, null, "None")]
		none = 419550000,
		
		/// <summary>
		/// Bot Session is resolved
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("resolved", 1, null, "Bot Session is resolved")]
		resolved = 419550001,
	}
}
#pragma warning restore CS1591
