#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Time Cost Actuals Source
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_TimeCostActualsSource
	{
		
		/// <summary>
		/// Booking Journals on Post of Work Order
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Booking Journals on Post of Work Order", 0, "#0000ff", "Booking Journals on Post of Work Order")]
		BookingJournalsonPostofWorkOrder = 192354000,
		
		/// <summary>
		/// Work Order Time Entry Approval
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work Order Time Entry Approval", 1, "#0000ff", "Work Order Time Entry Approval")]
		WorkOrderTimeEntryApproval = 192354001,
	}
}
#pragma warning restore CS1591
