#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// category can be User/Contact/Account/Lead/Opportunity
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_SmsTemplate_Category
	{
		
		/// <summary>
		/// Account
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Account", 0, "#0000ff", "Account", "account")]
		Account = 1,
		
		/// <summary>
		/// Contact
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Contact", 1, "#0000ff", "Contact", "contact")]
		Contact = 2,
		
		/// <summary>
		/// Lead
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lead", 3, "#0000ff", "Lead", "lead")]
		Lead = 4,
		
		/// <summary>
		/// Opportunity
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Opportunity", 2, "#0000ff", "Opportunity", "opportunity")]
		Opportunity = 3,
		
		/// <summary>
		/// User
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("User", 4, "#0000ff", "User", "user")]
		User = 8,
	}
}
#pragma warning restore CS1591
