#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_LiveWorkItemEventType
	{
		
		/// <summary>
		/// This event is triggered when the chat context is updated.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ContextUpdated", 2, "#0000ff", "This event is triggered when the chat context is updated.")]
		ContextUpdated = 192350002,
		
		/// <summary>
		/// This event is triggered when a customer initiates a conversation, that is when a live work item is created.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Created", 1, "#0000ff", "This event is triggered when a customer initiates a conversation, that is when a " +
			"live work item is created.")]
		Created = 192350001,
		
		/// <summary>
		/// This event is triggered when a chat is rejoined.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CustomerRejoin", 3, "#0000ff", "This event is triggered when a chat is rejoined.")]
		CustomerRejoin = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Default", 0, "#0000ff")]
		Default = 192350000,
		
		/// <summary>
		/// This event is triggered when a skill is updated during chat.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SkillIdentified", 4, "#0000ff", "This event is triggered when a skill is updated during chat.")]
		SkillIdentified = 192350005,
	}
}
#pragma warning restore CS1591
