#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Action to be taken due to overflow
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_OverflowActionType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Default", 0, "#0000ff")]
		Default = 192350000,
		
		/// <summary>
		/// Initiate callback for the customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Direct Callback", 3, "#0000ff", "Initiate callback for the customer")]
		DirectCallback = 192350003,
		
		/// <summary>
		/// Close the conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("End Conversation", 1, "#0000ff", "Close the conversation")]
		EndConversation = 192350001,
		
		/// <summary>
		/// Transfer work item to another queue
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue Transfer", 5, "#0000ff", "Transfer work item to another queue")]
		QueueTransfer = 192350005,
		
		/// <summary>
		/// Keep work item waiting in queue for agent assignment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Remain In Queue", 6, "#0000ff", "Keep work item waiting in queue for agent assignment")]
		RemainInQueue = 192350006,
		
		/// <summary>
		/// Transfer call to an external number
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transfer to Phone", 2, "#0000ff", "Transfer call to an external number")]
		TransfertoPhone = 192350002,
		
		/// <summary>
		/// Transfer call to voicemail
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Voicemail", 4, "#0000ff", "Transfer call to voicemail")]
		Voicemail = 192350004,
	}
}
#pragma warning restore CS1591
