#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// The type of an event parameter used by Cxp Events
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsDynMkt_EventParameterType
	{
		
		/// <summary>
		/// Event Parameter's value comes from a CDP-A built-in signal property. e.g. Signal.User.Id.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CDP-A Built-in Signal Property", 1, "#0000ff", "Event Parameter\'s value comes from a CDP-A built-in signal property. e.g. Signal." +
			"User.Id.")]
		CDPABuiltinSignalProperty = 534130001,
		
		/// <summary>
		/// Event Parameter's value comes from a CDP-A contactable signal property provided by the signal producer.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CDP-A Contactable Signal Property", 3, "#0000ff", "Event Parameter\'s value comes from a CDP-A contactable signal property provided b" +
			"y the signal producer.")]
		CDPAContactableSignalProperty = 534130003,
		
		/// <summary>
		/// Event Parameter's value comes from a CDP-A Event Binding signal property provided by the signal producer.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CDP-A Event Binding Signal Property", 4, "#0000ff", "Event Parameter\'s value comes from a CDP-A Event Binding signal property provided" +
			" by the signal producer.")]
		CDPAEventBindingSignalProperty = 534130004,
		
		/// <summary>
		/// Event Parameter's value comes from a CDP-A signal property explicitly provided by the signal producer.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CDP-A Signal Property", 2, "#0000ff", "Event Parameter\'s value comes from a CDP-A signal property explicitly provided by" +
			" the signal producer.")]
		CDPASignalProperty = 534130002,
		
		/// <summary>
		/// Event Parameter contains a Customer Identifier
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer Identifier", 0, "#0000ff", "Event Parameter contains a Customer Identifier")]
		CustomerIdentifier = 534130000,
	}
}
#pragma warning restore CS1591
