#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Stores the list of types of system messages.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_OCSystemMessageType
	{
		
		/// <summary>
		/// Automated Message
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Automated Message", 0, "#0000ff", "Automated Message")]
		AutomatedMessage = 2,
		
		/// <summary>
		/// Message Template
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Message Template", 1, "#0000ff", "Message Template")]
		MessageTemplate = 3,
	}
}
#pragma warning restore CS1591
