#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Frequency at which timestamps are generated
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_TimestampFrequency
	{
		
		/// <summary>
		/// Per Booking Status Change
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Per Booking Status Change", 0, "#0000ff", "Per Booking Status Change")]
		PerBookingStatusChange = 192350000,
		
		/// <summary>
		/// Per Field Service Status Change
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Per Field Service Status Change", 1, "#0000ff", "Per Field Service Status Change")]
		PerFieldServiceStatusChange = 192350001,
	}
}
#pragma warning restore CS1591
