#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Copilot product type picker
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_ViVaCopilotType
	{
		
		/// <summary>
		/// Represents records related to Sales Copilot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Copilot for Sales", 0, null, "Represents records related to Sales Copilot")]
		CopilotforSales = 10000,
		
		/// <summary>
		/// Represents records related to Service Copilot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Copilot for Service", 1, null, "Represents records related to Service Copilot")]
		CopilotforService = 10001,
		
		/// <summary>
		/// Represents records that are shared across different Copilot types
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Shared", 2, null, "Represents records that are shared across different Copilot types")]
		Shared = 11000,
	}
}
#pragma warning restore CS1591
