#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Defines the type for ML model
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_MlModelType
	{
		
		/// <summary>
		/// Routing using Effort ML model
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Effort based", 2, null, "Routing using Effort ML model")]
		Effortbased = 192350002,
		
		/// <summary>
		/// Routing using Sentiment ML model
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sentiment based", 1, null, "Routing using Sentiment ML model")]
		Sentimentbased = 192350001,
		
		/// <summary>
		/// Skill identification using ML model
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Skill based", 0, null, "Skill identification using ML model")]
		Skillbased = 192350000,
	}
}
#pragma warning restore CS1591
