#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// The power bi workspace type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_WorkspaceType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CustomerOwned", 1, "#0000ff")]
		CustomerOwned = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Managed", 0, "#0000ff")]
		Managed = 192350000,
	}
}
#pragma warning restore CS1591
