#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Available list of calling session event reason options
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_OCCallSessionEvenTreasons
	{
		
		/// <summary>
		/// Accepted
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Accepted", 19, "#0000ff", "Accepted")]
		Accepted = 192350019,
		
		/// <summary>
		/// AgentConversationJoin
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentConversationJoin", 40, "#0000ff", "AgentConversationJoin")]
		AgentConversationJoin = 192350041,
		
		/// <summary>
		/// AgentDisconnected
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentDisconnected", 10, "#0000ff", "AgentDisconnected")]
		AgentDisconnected = 192350010,
		
		/// <summary>
		/// AgentEndConsult
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentEndConsult", 31, "#0000ff", "AgentEndConsult")]
		AgentEndConsult = 192350032,
		
		/// <summary>
		/// AgentEndConversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentEndConversation", 30, "#0000ff", "AgentEndConversation")]
		AgentEndConversation = 192350030,
		
		/// <summary>
		/// AgentInviteRejected
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentInviteRejected", 8, "#0000ff", "AgentInviteRejected")]
		AgentInviteRejected = 192350008,
		
		/// <summary>
		/// AgentInviteTimeout
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentInviteTimeout", 9, "#0000ff", "AgentInviteTimeout")]
		AgentInviteTimeout = 192350009,
		
		/// <summary>
		/// AgentMonitor
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentMonitor", 39, "#0000ff", "AgentMonitor")]
		AgentMonitor = 192350040,
		
		/// <summary>
		/// AgentTimeout
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentTimeout", 11, "#0000ff", "AgentTimeout")]
		AgentTimeout = 192350011,
		
		/// <summary>
		/// AgentTransfer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentTransfer", 0, "#0000ff", "AgentTransfer")]
		AgentTransfer = 192350001,
		
		/// <summary>
		/// AgentTransferred
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentTransferred", 12, "#0000ff", "AgentTransferred")]
		AgentTransferred = 192350012,
		
		/// <summary>
		/// AssignToAgentBySupervisor  
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AssignToAgentBySupervisor  ", 26, "#0000ff", "AssignToAgentBySupervisor  ")]
		AssignToAgentBySupervisor = 192350026,
		
		/// <summary>
		/// AssignToQueueBySupervisor  
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AssignToQueueBySupervisor  ", 27, "#0000ff", "AssignToQueueBySupervisor  ")]
		AssignToQueueBySupervisor = 192350027,
		
		/// <summary>
		/// AutoAccept
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AutoAccept", 6, "#0000ff", "AutoAccept")]
		AutoAccept = 192350006,
		
		/// <summary>
		/// AutoAccepted
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AutoAccepted", 20, "#0000ff", "AutoAccepted")]
		AutoAccepted = 192350020,
		
		/// <summary>
		/// BotEndConversation 
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BotEndConversation ", 25, "#0000ff", "BotEndConversation ")]
		BotEndConversation = 192350025,
		
		/// <summary>
		/// BotTransferSession 
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BotTransferSession ", 24, "#0000ff", "BotTransferSession ")]
		BotTransferSession = 192350024,
		
		/// <summary>
		/// Closed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Closed", 7, "#0000ff", "Closed")]
		Closed = 192350007,
		
		/// <summary>
		/// Consult
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Consult", 38, "#0000ff", "Consult")]
		Consult = 192350039,
		
		/// <summary>
		/// ConversationExpired
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ConversationExpired", 37, "#0000ff", "ConversationExpired")]
		ConversationExpired = 192350038,
		
		/// <summary>
		/// CustomerDisconnect
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CustomerDisconnect", 14, "#0000ff", "CustomerDisconnect")]
		CustomerDisconnect = 192350014,
		
		/// <summary>
		/// CustomerEndConversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CustomerEndConversation", 29, "#0000ff", "CustomerEndConversation")]
		CustomerEndConversation = 192350029,
		
		/// <summary>
		/// CustomerRejoin
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CustomerRejoin", 28, "#0000ff", "CustomerRejoin")]
		CustomerRejoin = 192350028,
		
		/// <summary>
		/// CustomerTimeout
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CustomerTimeout", 13, "#0000ff", "CustomerTimeout")]
		CustomerTimeout = 192350013,
		
		/// <summary>
		/// Default
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Default", 42, "#0000ff", "Default")]
		Default = 192350000,
		
		/// <summary>
		/// Disconnect
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Disconnect", 21, "#0000ff", "Disconnect")]
		Disconnect = 192350021,
		
		/// <summary>
		/// End
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("End", 23, "#0000ff", "End")]
		End = 192350023,
		
		/// <summary>
		/// Escalated
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Escalated", 16, "#0000ff", "Escalated")]
		Escalated = 192350016,
		
		/// <summary>
		/// ForceClose
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ForceClose", 32, "#0000ff", "ForceClose")]
		ForceClose = 192350033,
		
		/// <summary>
		/// OverflowAssignToQueue
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OverflowAssignToQueue", 35, "#0000ff", "OverflowAssignToQueue")]
		OverflowAssignToQueue = 192350036,
		
		/// <summary>
		/// OverflowEndConversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OverflowEndConversation", 34, "#0000ff", "OverflowEndConversation")]
		OverflowEndConversation = 192350035,
		
		/// <summary>
		/// OverflowQueueTransfer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OverflowQueueTransfer", 33, "#0000ff", "OverflowQueueTransfer")]
		OverflowQueueTransfer = 192350034,
		
		/// <summary>
		/// PostchatSurvey
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PostchatSurvey", 4, "#0000ff", "PostchatSurvey")]
		PostchatSurvey = 192350004,
		
		/// <summary>
		/// PreChatSurvey
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PreChatSurvey", 3, "#0000ff", "PreChatSurvey")]
		PreChatSurvey = 192350003,
		
		/// <summary>
		/// Preview
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Preview", 41, "#0000ff", "Preview")]
		Preview = 192350042,
		
		/// <summary>
		/// QueueTransfer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("QueueTransfer", 2, "#0000ff", "QueueTransfer")]
		QueueTransfer = 192350002,
		
		/// <summary>
		/// Rejected
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Rejected", 17, "#0000ff", "Rejected")]
		Rejected = 192350017,
		
		/// <summary>
		/// SessionEndAfterWrapUp
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SessionEndAfterWrapUp", 36, "#0000ff", "SessionEndAfterWrapUp")]
		SessionEndAfterWrapUp = 192350037,
		
		/// <summary>
		/// SessionTimeout
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SessionTimeout", 15, "#0000ff", "SessionTimeout")]
		SessionTimeout = 192350015,
		
		/// <summary>
		/// Default
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SupervisorTransferToAgent", 1, "#0000ff", "Default")]
		SupervisorTransferToAgent = 192350031,
		
		/// <summary>
		/// TimedOut
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("TimedOut", 18, "#0000ff", "TimedOut")]
		TimedOut = 192350018,
		
		/// <summary>
		/// Timeout
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Timeout", 22, "#0000ff", "Timeout")]
		Timeout = 192350022,
		
		/// <summary>
		/// UserAccept
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("UserAccept", 5, "#0000ff", "UserAccept")]
		UserAccept = 192350005,
	}
}
#pragma warning restore CS1591
