#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Show desktop notifications
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_DesktopNotificationSettings
	{
		
		/// <summary>
		/// Never
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Never", 0, "#AA0000", "Never")]
		Never = 100000002,
		
		/// <summary>
		/// When app is in background
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("When app is in background", 1, "#000000", "When app is in background")]
		Whenappisinbackground = 100000003,
	}
}
#pragma warning restore CS1591
