#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Ordering of teams for scheduling a requirement group.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_RequirementGroupOrder
	{
		
		/// <summary>
		/// Sort by the earliest start time.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Earliest Time First", 1, "#0000ff", "Sort by the earliest start time.")]
		EarliestTimeFirst = 690970001,
		
		/// <summary>
		/// Sort by the number of resources needed to satisfy the set of requirements in ascending order.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fewest Resources First", 0, "#0000ff", "Sort by the number of resources needed to satisfy the set of requirements in asce" +
			"nding order.")]
		FewestResourcesFirst = 690970000,
	}
}
#pragma warning restore CS1591
