#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Type of not-to-exceed amount.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_NTeType
	{
		
		/// <summary>
		/// Indicates not-to-exceed amount for Costs from vendors.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cost", 1, "#7CB9E8", "Indicates not-to-exceed amount for Costs from vendors.")]
		Cost = 192350200,
		
		/// <summary>
		/// Indicates not-to-exceed amount for Customer.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Price", 0, "#0048BA", "Indicates not-to-exceed amount for Customer.")]
		Price = 192350100,
		
		/// <summary>
		/// Indicates not-to-exceed amount for Price, and Cost based on specifed margin from Price.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Price and cost margin", 2, "#006b76", "Indicates not-to-exceed amount for Price, and Cost based on specifed margin from " +
			"Price.")]
		Priceandcostmargin = 192350300,
	}
}
#pragma warning restore CS1591
