#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Time Entry Generation Strategy
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_TimeEntryGenerationStrategy
	{
		
		/// <summary>
		/// Select this option in order for the system to automatically generate time entries based on booking timestamps.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Auto-Generate from Booking Timestamps", 1, "#0000ff", "Select this option in order for the system to automatically generate time entries" +
			" based on booking timestamps.")]
		AutoGeneratefromBookingTimestamps = 192355201,
		
		/// <summary>
		/// Select this option to manually generate time entries of bookings.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Manual", 0, "#0000ff", "Select this option to manually generate time entries of bookings.")]
		Manual = 192355200,
	}
}
#pragma warning restore CS1591
