#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Event Metadata Status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsDynMkt_EventMetadataStatus
	{
		
		/// <summary>
		/// Draft status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Draft", 0, "#0000ff", "Draft status")]
		Draft = 534120000,
		
		/// <summary>
		/// Published status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Published", 1, "#0000ff", "Published status")]
		Published = 534120001,
		
		/// <summary>
		/// Stopped status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Stopped", 2, "#0000ff", "Stopped status")]
		Stopped = 534120002,
	}
}
#pragma warning restore CS1591
