#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Defines the repeat of booking by a daily, weekly, monthly or yearly frequency
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_RecurrencePattern
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Daily", 0, "#0000ff")]
		Daily = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Monthly", 2, "#0000ff")]
		Monthly = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Weekly", 1, "#0000ff")]
		Weekly = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Yearly", 3, "#0000ff")]
		Yearly = 192350003,
	}
}
#pragma warning restore CS1591
