#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Event Metadata Integration Status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsDynMkt_EventMetadataIntegrationStatus
	{
		
		/// <summary>
		/// Integrated status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Integrated", 1, "#0000ff", "Integrated status")]
		Integrated = 534120001,
		
		/// <summary>
		/// Not Integrated status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("NotIntegrated", 2, "#0000ff", "Not Integrated status")]
		NotIntegrated = 534120002,
		
		/// <summary>
		/// Unknown integration status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Unknown", 0, "#0000ff", "Unknown integration status")]
		Unknown = 534120000,
	}
}
#pragma warning restore CS1591
