#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Defines routing status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_Msdyn_UnifiedRoutingRun_Msdyn_RoutingStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent assignment - completed", 6, "#0000ff")]
		Agentassignmentcompleted = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Intake rules - completed", 0, "#0000ff")]
		Intakerulescompleted = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue: Assignment rules - completed", 5, "#0000ff")]
		QueueAssignmentrulescompleted = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue: Assignment selection rules - completed", 4, "#0000ff")]
		QueueAssignmentselectionrulescompleted = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue: Prioritization rules - completed", 3, "#0000ff")]
		QueuePrioritizationrulescompleted = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Workstream: Classification rules - processing...", 1, "#0000ff")]
		WorkstreamClassificationrulesprocessing = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Workstream: Route-to-queue rules - completed", 2, "#0000ff")]
		WorkstreamRoutetoqueuerulescompleted = 100000002,
	}
}
#pragma warning restore CS1591
