#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Sequence Step Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_SequenceStep_Type
	{
		
		/// <summary>
		/// Automatic action step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Auto action", 7, "#0000ff", "Automatic action step")]
		Autoaction = 4,
		
		/// <summary>
		/// Automated Email step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Automated Email", 6, "#0000ff", "Automated Email step")]
		AutomatedEmail = 3,
		
		/// <summary>
		/// Automated Experimentation step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Automated Experimentation", 10, "#0000ff", "Automated Experimentation step")]
		AutomatedExperimentation = 7,
		
		/// <summary>
		/// Automated text message step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Automated text message", 9, "#0000ff", "Automated text message step")]
		Automatedtextmessage = 6,
		
		/// <summary>
		/// Email Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 3, "#0000ff", "Email Step")]
		Email = 4202,
		
		/// <summary>
		/// LinkedIn action step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("LinkedIn action", 8, "#0000ff", "LinkedIn action step")]
		LinkedInaction = 5,
		
		/// <summary>
		/// Phone call step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Phone call", 4, "#0000ff", "Phone call step")]
		Phonecall = 4210,
		
		/// <summary>
		/// Simple Condition Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Simple Condition", 0, "#0000ff", "Simple Condition Step")]
		SimpleCondition = 1,
		
		/// <summary>
		/// Task Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Task", 1, "#0000ff", "Task Step")]
		Task = 4212,
		
		/// <summary>
		/// Text message step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Text message", 2, "#0000ff", "Text message step")]
		Textmessage = 4213,
		
		/// <summary>
		/// Wait Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Wait", 5, "#0000ff", "Wait Step")]
		Wait = 0,
	}
}
#pragma warning restore CS1591
