#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Indicates model's recent training status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_OcSkillIdentMlModelTrainingStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Loading data", 7)]
		Loadingdata = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not trained", 0, "#0000ff")]
		Nottrained = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Publish completed", 6)]
		Publishcompleted = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Publish failed", 5)]
		Publishfailed = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Publish in progress", 4)]
		Publishinprogress = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Training completed", 2, "#0000ff")]
		Trainingcompleted = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Training failed", 3, "#0000ff")]
		Trainingfailed = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Training in progress", 1, "#0000ff")]
		Traininginprogress = 100000001,
	}
}
#pragma warning restore CS1591
