#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// The type of time entry
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_TimeEntryType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Absence", 2)]
		Absence = 192350001,
		
		/// <summary>
		/// On Break
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("On Break", 4, "#0000ff", "On Break")]
		OnBreak = 192355000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Overtime", 0, "#0000ff")]
		Overtime = 192354320,
		
		/// <summary>
		/// Travel
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Travel", 5, "#0000ff", "Travel")]
		Travel = 192355001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vacation", 3)]
		Vacation = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Work", 1)]
		Work = 192350000,
	}
}
#pragma warning restore CS1591
