#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Status/Outcome of an UpgradeRun, UpgradeVersion, and UpgradeStep: started/success/failure
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_UpgradeStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Failure", 2, "#c00000")]
		Failure = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Started", 0, "#0000ff")]
		Started = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Success", 1, "#008000")]
		Success = 100000001,
	}
}
#pragma warning restore CS1591
