#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Stores the list of event types for system messages.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_OCSystemMessageEventType
	{
		
		/// <summary>
		/// Agent accepted consult conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent accepted consult conversation", 60, "#0000ff", "Agent accepted consult conversation")]
		Agentacceptedconsultconversation = 192350060,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent assigned to conversation", 17, "#0000ff")]
		Agentassignedtoconversation = 192350017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent couldn\'t be assigned to conversation", 18, "#0000ff")]
		Agentcouldntbeassignedtoconversation = 192350018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent disconnected from conversation", 13, "#0000ff")]
		Agentdisconnectedfromconversation = 192350013,
		
		/// <summary>
		/// Agent ended consult conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent ended consult conversation", 62, "#0000ff", "Agent ended consult conversation")]
		Agentendedconsultconversation = 192350062,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent ended conversation", 14, "#0000ff")]
		Agentendedconversation = 192350014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent joined conversation", 0, "#0000ff")]
		Agentjoinedconversation = 192350000,
		
		/// <summary>
		/// Agent joined customer conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent joined customer conversation", 61, "#0000ff", "Agent joined customer conversation")]
		Agentjoinedcustomerconversation = 192350061,
		
		/// <summary>
		/// Agent left consult conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent left consult conversation", 58, "#0000ff", "Agent left consult conversation")]
		Agentleftconsultconversation = 192350058,
		
		/// <summary>
		/// Agent left customer conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent left customer conversation", 59, "#0000ff", "Agent left customer conversation")]
		Agentleftcustomerconversation = 192350059,
		
		/// <summary>
		/// Agent removed from consult conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent removed from consult conversation", 63, "#0000ff", "Agent removed from consult conversation")]
		Agentremovedfromconsultconversation = 192350063,
		
		/// <summary>
		/// Agent's message couldn't be sent
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent\'s message couldn\'t be sent", 22, "#0000ff", "Agent\'s message couldn\'t be sent")]
		Agentsmessagecouldntbesent = 192350022,
		
		/// <summary>
		/// Average wait time for customers: Hours
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Average wait time for customers: Hours", 31, "#0000ff", "Average wait time for customers: Hours")]
		AveragewaittimeforcustomersHours = 192350031,
		
		/// <summary>
		/// Average wait time for customers: Hours and minutes
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Average wait time for customers: Hours and minutes", 32, "#0000ff", "Average wait time for customers: Hours and minutes")]
		AveragewaittimeforcustomersHoursandminutes = 192350032,
		
		/// <summary>
		/// Average wait time for customers: Minutes
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Average wait time for customers: Minutes", 30, "#0000ff", "Average wait time for customers: Minutes")]
		AveragewaittimeforcustomersMinutes = 192350030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Consult accepted", 1, "#0000ff")]
		Consultaccepted = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Consult rejected", 7, "#0000ff")]
		Consultrejected = 192350007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Consult request failed", 4, "#0000ff")]
		Consultrequestfailed = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Consult request timed out", 9, "#0000ff")]
		Consultrequesttimedout = 192350009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Consult session ended", 16, "#0000ff")]
		Consultsessionended = 192350016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Consult started", 3, "#0000ff")]
		Consultstarted = 192350003,
		
		/// <summary>
		/// Couldn’t find the channel account in Omnichannel
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Couldn’t find the channel account in Omnichannel", 37, "#0000ff", "Couldn’t find the channel account in Omnichannel")]
		CouldntfindthechannelaccountinOmnichannel = 192350037,
		
		/// <summary>
		/// Customer callback response
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer callback response", 69, "#0000ff", "Customer callback response")]
		Customercallbackresponse = 192350074,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer disconnected", 20, "#0000ff")]
		Customerdisconnected = 192350020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer ended conversation", 19, "#0000ff")]
		Customerendedconversation = 192350019,
		
		/// <summary>
		/// Customer has opted out from Async Conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer has opted out from Async Conversation", 57, "#0000ff", "Customer has opted out from Async Conversation")]
		CustomerhasoptedoutfromAsyncConversation = 192350057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer is next in line", 24, "#0000ff")]
		Customerisnextinline = 192350024,
		
		/// <summary>
		/// Customer no longer on hold.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer no longer on hold.", 43, "#0000ff", "Customer no longer on hold.")]
		Customernolongeronhold = 192350043,
		
		/// <summary>
		/// Customer put on hold.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer put on hold.", 42, "#0000ff", "Customer put on hold.")]
		Customerputonhold = 192350042,
		
		/// <summary>
		/// Customer's file couldn't be attached because it's too big
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer\'s file couldn\'t be attached because it\'s too big", 38, "#0000ff", "Customer\'s file couldn\'t be attached because it\'s too big")]
		Customersfilecouldntbeattachedbecauseitstoobig = 192350038,
		
		/// <summary>
		/// Customer's message couldn't be sent: Outside of operation hours
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer\'s message couldn\'t be sent: Outside of operation hours", 23, "#0000ff", "Customer\'s message couldn\'t be sent: Outside of operation hours")]
		CustomersmessagecouldntbesentOutsideofoperationhours = 192350023,
		
		/// <summary>
		/// Customer's message couldn't be sent: Service is down.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer\'s message couldn\'t be sent: Service is down.", 70, "#0000ff", "Customer\'s message couldn\'t be sent: Service is down.")]
		CustomersmessagecouldntbesentServiceisdown = 192370001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer\'s position in queue", 21, "#0000ff")]
		Customerspositioninqueue = 192350021,
		
		/// <summary>
		/// Ending the conversation when queue overflow condition met
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("End conversation due to overflow", 55, "#0000ff", "Ending the conversation when queue overflow condition met")]
		Endconversationduetooverflow = 192350055,
		
		/// <summary>
		/// Greeting Message for Async Channels and Voice
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Greeting Message for Async Channels and Voice", 56, "#0000ff", "Greeting Message for Async Channels and Voice")]
		GreetingMessageforAsyncChannelsandVoice = 192350056,
		
		/// <summary>
		/// Holiday message to customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Holiday message to customer", 35, "#0000ff", "Holiday message to customer")]
		Holidaymessagetocustomer = 192350035,
		
		/// <summary>
		/// Invalid Apple OAuth response
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Invalid Apple OAuth response", 66, "#0000ff", "Invalid Apple OAuth response")]
		InvalidAppleOAuthresponse = 192350071,
		
		/// <summary>
		/// Leave as many messages as you’d like and we’ll get back to you as soon as possible. We’ll save your chat history, so you can leave and come back anytime.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Leave as many messages as you’d like and we’ll get back to you as soon as possibl" +
			"e. We’ll save your chat history, so you can leave and come back anytime.", 41, "#0000ff", "Leave as many messages as you’d like and we’ll get back to you as soon as possibl" +
			"e. We’ll save your chat history, so you can leave and come back anytime.")]
		LeaveasmanymessagesasyoudlikeandwellgetbacktoyouassoonaspossibleWellsaveyourchathistorysoyoucanleaveandcomebackanytime = 192350041,
		
		/// <summary>
		/// Message couldn't be delivered: Unsupported message type
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Message couldn\'t be delivered: Unsupported message type", 25, "#0000ff", "Message couldn\'t be delivered: Unsupported message type")]
		MessagecouldntbedeliveredUnsupportedmessagetype = 192350025,
		
		/// <summary>
		/// Message couldn’t be sent: A channel account can’t message another account within Omnichannel
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Message couldn’t be sent: A channel account can’t message another account within " +
			"Omnichannel", 34, "#0000ff", "Message couldn’t be sent: A channel account can’t message another account within " +
			"Omnichannel")]
		MessagecouldntbesentAchannelaccountcantmessageanotheraccountwithinOmnichannel = 192350034,
		
		/// <summary>
		/// Message couldn’t be sent: File couldn’t be attached
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Message couldn’t be sent: File couldn’t be attached", 40, "#0000ff", "Message couldn’t be sent: File couldn’t be attached")]
		MessagecouldntbesentFilecouldntbeattached = 192350040,
		
		/// <summary>
		/// Message couldn't be sent: Outside allowed timeframe
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Message couldn\'t be sent: Outside allowed timeframe", 29, "#0000ff", "Message couldn\'t be sent: Outside allowed timeframe")]
		MessagecouldntbesentOutsideallowedtimeframe = 192350029,
		
		/// <summary>
		/// Message or attachment failed to send. Providing error details including error code, reason for failure, message id, timestamp, and transaction id
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Message or attachment failed to send. Providing error details including error cod" +
			"e, reason for failure, message id, timestamp, and transaction id", 44, "#0000ff", "Message or attachment failed to send. Providing error details including error cod" +
			"e, reason for failure, message id, timestamp, and transaction id")]
		MessageorattachmentfailedtosendProvidingerrordetailsincludingerrorcodereasonforfailuremessageidtimestampandtransactionid = 192350044,
		
		/// <summary>
		/// Message displayed to customer when there is not enough data to show the average wait time when the feature has been enabled
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not enough data for average wait time", 64, "#0000ff", "Message displayed to customer when there is not enough data to show the average w" +
			"ait time when the feature has been enabled")]
		Notenoughdataforaveragewaittime = 192350064,
		
		/// <summary>
		/// Offer customer callback
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Offer customer callback", 68, "#0000ff", "Offer customer callback")]
		Offercustomercallback = 192350073,
		
		/// <summary>
		/// Out of operating hour message to customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Out of operating hour message to customer", 36, "#0000ff", "Out of operating hour message to customer")]
		Outofoperatinghourmessagetocustomer = 192350036,
		
		/// <summary>
		/// Recording and transcription paused.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Recording and transcription paused.", 50, "#0000ff", "Recording and transcription paused.")]
		Recordingandtranscriptionpaused = 192350050,
		
		/// <summary>
		/// Recording and transcription resumed.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Recording and transcription resumed.", 51, "#0000ff", "Recording and transcription resumed.")]
		Recordingandtranscriptionresumed = 192350051,
		
		/// <summary>
		/// Recording and transcription started.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Recording and transcription started.", 49, "#0000ff", "Recording and transcription started.")]
		Recordingandtranscriptionstarted = 192350049,
		
		/// <summary>
		/// Recording and transcription stopped.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Recording and transcription stopped.", 52, "#0000ff", "Recording and transcription stopped.")]
		Recordingandtranscriptionstopped = 192350052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Session ended", 15, "#0000ff")]
		Sessionended = 192350015,
		
		/// <summary>
		/// Supervisor force closed the conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Supervisor force closed the conversation", 67, "#0000ff", "Supervisor force closed the conversation")]
		Supervisorforceclosedtheconversation = 192350072,
		
		/// <summary>
		/// Transcription paused.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transcription paused.", 46, "#0000ff", "Transcription paused.")]
		Transcriptionpaused = 192350046,
		
		/// <summary>
		/// Transcription resumed.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transcription resumed.", 47, "#0000ff", "Transcription resumed.")]
		Transcriptionresumed = 192350047,
		
		/// <summary>
		/// Transcription started.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transcription started.", 45, "#0000ff", "Transcription started.")]
		Transcriptionstarted = 192350045,
		
		/// <summary>
		/// Transcription stopped.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transcription stopped.", 48, "#0000ff", "Transcription stopped.")]
		Transcriptionstopped = 192350048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transfer to agent accepted", 2, "#0000ff")]
		Transfertoagentaccepted = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transfer to agent failed", 6, "#0000ff")]
		Transfertoagentfailed = 192350006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transfer to agent rejected", 8, "#0000ff")]
		Transfertoagentrejected = 192350008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transfer to agent requested", 5, "#0000ff")]
		Transfertoagentrequested = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transfer to agent timed out", 10, "#0000ff")]
		Transfertoagenttimedout = 192350010,
		
		/// <summary>
		/// Transfer to out of operating hour queue
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transfer to out of operating hour queue", 39, "#0000ff", "Transfer to out of operating hour queue")]
		Transfertooutofoperatinghourqueue = 192350039,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transfer to queue failed", 12, "#0000ff")]
		Transfertoqueuefailed = 192350012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transfer to queue started", 11, "#0000ff")]
		Transfertoqueuestarted = 192350011,
		
		/// <summary>
		/// Time limit for a trial conversation exceeded
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Trial conversation time limit exceeded", 54, "#0000ff", "Time limit for a trial conversation exceeded")]
		Trialconversationtimelimitexceeded = 192350054,
		
		/// <summary>
		/// Usage limit for trial exceeded limits
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Trial usage limit exceeded", 53, "#0000ff", "Usage limit for trial exceeded limits")]
		Trialusagelimitexceeded = 192350053,
		
		/// <summary>
		/// Voice call accepted
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Voice call accepted", 27, "#0000ff", "Voice call accepted")]
		Voicecallaccepted = 192350027,
		
		/// <summary>
		/// Voice call declined
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Voice call declined", 28, "#0000ff", "Voice call declined")]
		Voicecalldeclined = 192350028,
		
		/// <summary>
		/// Voice call ended
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Voice call ended", 33, "#0000ff", "Voice call ended")]
		Voicecallended = 192350033,
		
		/// <summary>
		/// Voice call requested
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Voice call requested", 26, "#0000ff", "Voice call requested")]
		Voicecallrequested = 192350026,
		
		/// <summary>
		/// Message displayed to agent when customer is disconnected from conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Waiting time for agent when customer is disconnected", 65, "#0000ff", "Message displayed to agent when customer is disconnected from conversation")]
		Waitingtimeforagentwhencustomerisdisconnected = 192350070,
	}
}
#pragma warning restore CS1591
