#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PowerBiMashupParameterValueSource
	{
		
		/// <summary>
		/// The value for the parameter is set to the domain of the current environment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Environment Domain", 2, "#0000ff", "The value for the parameter is set to the domain of the current environment")]
		EnvironmentDomain = 200000002,
		
		/// <summary>
		/// The value for the parameter is bound to an environment variable
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Environment Variable", 1, "#0000ff", "The value for the parameter is bound to an environment variable")]
		EnvironmentVariable = 200000001,
		
		/// <summary>
		/// The value for the parameter is provided as text
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Literal", 0, "#0000ff", "The value for the parameter is provided as text")]
		Literal = 200000000,
	}
}
#pragma warning restore CS1591
