#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Based on the options in SkipPriceCalculation , OOB price calculation for  qooi level will be skipped
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum QOOI_SkipPriceCalculation
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DoPriceCalcAlways", 0)]
		DoPriceCalcAlways = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SkipPriceCalcOnRetrieve", 1)]
		SkipPriceCalcOnRetrieve = 1,
	}
}
#pragma warning restore CS1591
