#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Week of the month used under Monthly/Yearly recurrence patterns
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SameWeekWeek_Options
	{
		
		/// <summary>
		/// First week of the month
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("First", 0, "#0000ff", "First week of the month")]
		First = 1,
		
		/// <summary>
		/// Fourth week of the month
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fourth", 3, "#0000ff", "Fourth week of the month")]
		Fourth = 4,
		
		/// <summary>
		/// Last week of the month
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Last", 4, "#0000ff", "Last week of the month")]
		Last = 5,
		
		/// <summary>
		/// Second week of the month
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Second", 1, "#0000ff", "Second week of the month")]
		Second = 2,
		
		/// <summary>
		/// Third week of the month
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Third", 2, "#0000ff", "Third week of the month")]
		Third = 3,
	}
}
#pragma warning restore CS1591
