#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Location type of the SharePoint document location.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SharePointDocumentLocation_LocationType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dedicated for OneNote Integration", 1)]
		DedicatedforOneNoteIntegration = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("General", 0)]
		General = 0,
	}
}
#pragma warning restore CS1591
