#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Validation status reason of the record URL.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SharePoint_ValidationStatusReason
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Authentication failure.", 5)]
		Authenticationfailure = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Invalid certificates.", 6)]
		Invalidcertificates = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("The URL could not be accessed because of Internet Explorer security settings.", 4)]
		TheURLcouldnotbeaccessedbecauseofInternetExplorersecuritysettings = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("The URL schemes of Microsoft Dynamics 365 and SharePoint are different.", 3)]
		TheURLschemesofMicrosoftDynamics365andSharePointaredifferent = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("This record\'s URL has not been validated.", 0)]
		ThisrecordsURLhasnotbeenvalidated = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("This record\'s URL is not valid.", 2)]
		ThisrecordsURLisnotvalid = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("This record\'s URL is valid.", 1)]
		ThisrecordsURLisvalid = 2,
	}
}
#pragma warning restore CS1591
