#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Select the entity for which SLA is to be created
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Sla_SlaEnabledEntities
	{
		
		/// <summary>
		/// Anfrage für Serviceanforderung, die einem Vertrag zugeordnet ist.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Case", 2, null, "Anfrage für Serviceanforderung, die einem Vertrag zugeordnet ist.")]
		Case = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lead", 3)]
		Lead = 4,
		
		/// <summary>
		/// Angebot, das angenommen wurde.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Order", 1, null, "Angebot, das angenommen wurde.")]
		Order = 1088,
		
		/// <summary>
		/// Formelles Angebot für Produkte und/oder Services zu bestimmten Preisen und entsprechenden Zahlungsbedingungen, das an einen potenziellen Kunden gesendet wird.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quote", 0, null, "Formelles Angebot für Produkte und/oder Services zu bestimmten Preisen und entspr" +
			"echenden Zahlungsbedingungen, das an einen potenziellen Kunden gesendet wird.")]
		Quote = 1084,
	}
}
#pragma warning restore CS1591
