#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Synapse Link destination sync state
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SynapseLinkDestinationSyncState
	{
		
		/// <summary>
		/// Completed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Completed", 2, "#0000ff", "Completed")]
		Completed = 2,
		
		/// <summary>
		/// None
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("None", 0, "#0000ff", "None")]
		None = 0,
		
		/// <summary>
		/// Not Completed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("NotCompleted", 1, "#0000ff", "Not Completed")]
		NotCompleted = 1,
	}
}
#pragma warning restore CS1591
