#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Synapse Link entity metadata state
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SynapseLinkEntityMetadataState
	{
		
		/// <summary>
		/// Created
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Created", 4, "#0000ff", "Created")]
		Created = 8,
		
		/// <summary>
		/// Failure
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Failure", 5, "#0000ff", "Failure")]
		Failure = 16,
		
		/// <summary>
		/// Metadata creating
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("MetadataCreating", 2, "#0000ff", "Metadata creating")]
		MetadataCreating = 2,
		
		/// <summary>
		/// None state for flag enumeration. Not a valid state for usage
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("None", 0, "#0000ff", "None state for flag enumeration. Not a valid state for usage")]
		None = 0,
		
		/// <summary>
		/// Not created
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("NotCreated", 1, "#0000ff", "Not created")]
		NotCreated = 1,
		
		/// <summary>
		/// Relationship creating
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RelationshipCreating", 3, "#0000ff", "Relationship creating")]
		RelationshipCreating = 4,
	}
}
#pragma warning restore CS1591
