#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Synapse Link entity partition strategy
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SynapseLinkEntityPartitionStrategy
	{
		
		/// <summary>
		/// FiveDay
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FiveDay", 3, "#0000ff", "FiveDay")]
		FiveDay = 3,
		
		/// <summary>
		/// HalfMonth
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("HalfMonth", 2, "#0000ff", "HalfMonth")]
		HalfMonth = 2,
		
		/// <summary>
		/// Month
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Month", 1, "#0000ff", "Month")]
		Month = 1,
		
		/// <summary>
		/// Year
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Year", 0, "#0000ff", "Year")]
		Year = 0,
	}
}
#pragma warning restore CS1591
