#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Synapse Link external table state
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SynapseLinkExternalTableState
	{
		
		/// <summary>
		/// Created
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Created", 1, "#0000ff", "Created")]
		Created = 1,
		
		/// <summary>
		/// Deleted
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Deleted", 3, "#0000ff", "Deleted")]
		Deleted = 3,
		
		/// <summary>
		/// Failed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Failed", 2, "#0000ff", "Failed")]
		Failed = 2,
		
		/// <summary>
		/// In Progress
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("In Progress", 4, "#0000ff", "In Progress")]
		InProgress = 4,
		
		/// <summary>
		/// Not created
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not Created", 0, "#0000ff", "Not created")]
		NotCreated = 0,
	}
}
#pragma warning restore CS1591
