#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Synapse Link table creation state
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SynapseLinkSynapseTableCreationState
	{
		
		/// <summary>
		/// Completed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Completed", 2, "#0000ff", "Completed")]
		Completed = 2,
		
		/// <summary>
		/// Failed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Failed", 3, "#0000ff", "Failed")]
		Failed = 3,
		
		/// <summary>
		/// In progress
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("InProgress", 1, "#0000ff", "In progress")]
		InProgress = 1,
		
		/// <summary>
		/// Not started
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("NotStarted", 0, "#0000ff", "Not started")]
		NotStarted = 0,
	}
}
#pragma warning restore CS1591
