#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Synapse Link profile type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SynapseLinkProFiletype
	{
		
		/// <summary>
		/// Event Analytics profile
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EventAnalytics", 1, "#0000ff", "Event Analytics profile")]
		EventAnalytics = 1,
		
		/// <summary>
		/// Synapse Link profile
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SynapseLink", 0, "#0000ff", "Synapse Link profile")]
		SynapseLink = 0,
	}
}
#pragma warning restore CS1591
